apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.fullLabels" "grafana" | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.grafana.pvc.storageClass }}
  storageClassName: {{ .Values.grafana.pvc.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.pvc.size }}
