apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.fullLabels" "grafana" | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "monitoring.selectorLabels" "grafana" | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: 3000
      protocol: TCP
