apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.fullLabels" "tempo" | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "monitoring.selectorLabels" "tempo" | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.tempo.service.httpPort }}
      targetPort: {{ .Values.tempo.service.httpPort }}
      protocol: TCP
    - name: otlp-grpc
      port: {{ .Values.tempo.service.otlpGrpcPort }}
      targetPort: {{ .Values.tempo.service.otlpGrpcPort }}
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.tempo.service.otlpHttpPort }}
      targetPort: {{ .Values.tempo.service.otlpHttpPort }}
      protocol: TCP
