# @format
# Development environment overrides â€” lower resource limits, smaller PVCs.

prometheus:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  pvc:
    size: 5Gi
  retention: 7d

grafana:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 128m
      memory: 128Mi
  pvc:
    size: 2Gi

loki:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 128m
      memory: 256Mi
  pvc:
    size: 5Gi

tempo:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 128m
      memory: 256Mi
  pvc:
    size: 5Gi

resourceQuota:
  hard:
    requests.cpu: "1500m"
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 4Gi
    persistentvolumeclaims: "6"
