apiVersion: v1
kind: Service
metadata:
  name: nextjs
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nextjs.fullLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nextjs.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
