apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.fullLabels" "grafana" | nindent 4 }}
type: Opaque
stringData:
  admin-user: admin
  admin-password: changeme
