apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.fullLabels" "prometheus" | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.prometheus.pvc.storageClass }}
  storageClassName: {{ .Values.prometheus.pvc.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.prometheus.pvc.size }}
